apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: smcatapan/color-api:1.2.1
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      env:
        - name: DELAY_STARTUP
          value: 'false'
        - name: FAIL_LIVENESS
          value: 'true'
      startupProbe:
        httpGet:
          path: /up
          port: 80
        failureThreshold: 2
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        failureThreshold: 3
        periodSeconds: 10