apiVersion: v1
kind: Pod
metadata:
  name: green-color-api
  labels:
    app: green-color-api
spec:
  containers:
  - name: green-color-api
    image: smcatapan/color-api:1.3.1
    env:
      - name: COLOR_CONFIG_PATH
        valueFrom:
          configMapKeyRef:
            name: green-env-vars
            key: COLOR_CONFIG_PATH
    volumeMounts:
      - name: color-config
        mountPath: /mnt/config
        readOnly: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: color-config
      configMap:
        name: green-files